services:
  sonobarr:
    image: ghcr.io/dodelidoo-labs/sonobarr:latest # or ghcr.io/dodelidoo-labs/sonobarr:0.1.0 for a specific version
    container_name: sonobarr
    volumes:
      - ./config:/sonobarr/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    environment:
      - last_fm_api_key=${last_fm_api_key}
      - last_fm_api_secret=${last_fm_api_secret}
      - lidarr_address=${lidarr_address}
      - quality_profile_id=${quality_profile_id}
      - lidarr_api_key=${lidarr_api_key}
      - youtube_api_key=${youtube_api_key}
    networks:
      npm_proxy:
        ipv4_address: 192.168.97.23 # change to an available IP on your proxy network

networks:
  npm_proxy:
    external: true
